fl=open('output8.txt','a')
a=[1,5,4,3,8,6,9,51,66,81,7,33]
print("befor sort")
print(a)
fl.write("befor sort\n"+str(a))
print("after ascending  sort")
a.sort()
print(a)
fl.write("\nafter ascending sort\n"+str(a))
print("after reverse or descending sort")
a.sort(reverse=True)
print(a)
fl.write("\nafter reverse or descending sort\n"+ str(a))
fl.close()